name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'apache/parquet-java version'
        default: '1.15.0'
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: apache/parquet-java
          ref: apache-parquet-${{ inputs.version }}
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          
      - run: |
          pushd parquet-cli
          sudo apt install -y thrift-compiler
          mvn clean package -DskipTests -Plocal 

      - uses: actions/upload-artifact@v4
        with:
          name: parquet-cli
          path: parquet-cli/target/parquet-cli-*-runtime.jar
      
