name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of apache/parquet-java to use (eg: 1.14.4)'
        default: '1.14.4'
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: apache/parquet-java
          ref: parquet-${{ inputs.version }}
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          
      - name: Build
        run: |
          pushd parquet-cli
          sudo apt install -y thrift-compiler
          mvn clean package -DskipTests -Plocal 
          java -jar target/parquet-cli-${{ inputs.version }}-runtime.jar

